# Generated by Django 3.2.3 on 2021-05-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_register_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_register',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='pics/'),
        ),
    ]
